apiVersion: apps/v1
kind: Deployment
metadata:
  name: planton-cloud-kube-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: planton-cloud-kube-agent
    company: {{ .Values.company }}
    hosting-env-id: {{ .Values.hostingEnvId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planton-cloud-kube-agent
      company: {{ .Values.company }}
      hosting-env-id: {{ .Values.hostingEnvId }}
  template:
    metadata:
      labels:
        app: planton-cloud-kube-agent
        company: {{ .Values.company }}
        hosting-env-id: {{ .Values.hostingEnvId }}
    spec:
      containers:
      - name: planton-cloud-kube-agent
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        env:
          - name: PLANTON_CLOUD_KUBE_AGENT_CLIENT_ID
            value: {{ .Values.clientId }}
          - name: PLANTON_CLOUD_KUBE_AGENT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: planton-cloud-machine-account
                key: client-secret
          - name: PLANTON_CLOUD_KUBE_AGENT_HOSTING_ENV_ID
            value: {{ .Values.hostingEnvId }}
          - name: PLANTON_CLOUD_SERVICE_API_ENDPOINT
            value: {{ .Values.plantonCloudServiceApiEndpoint }}
          - name: OPEN_COST_API_ENDPOINT
            value: {{ .Values.openCostApiEndpoint }}
          - name: OPEN_COST_POLLING_INTERVAL_SECONDS
            value: {{ .Values.openCostPollingIntervalSeconds }}
          - name: TOKEN_EXPIRATION_BUFFER_MINUTES
            value: {{ .Values.tokenExpirationBufferMinutes }}
          - name: TOKEN_EXPIRATION_CHECK_INTERVAL_SECONDS
            value: {{ .Values.tokenExpirationCheckIntervalSeconds }}
