apiVersion: apps/v1
kind: Deployment
metadata:
  name: planton-cloud-kube-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: planton-cloud-kube-agent
    company: {{ .Values.company }}
    hosting-env-id: {{ .Values.hostingClusterId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planton-cloud-kube-agent
      company: {{ .Values.company }}
      hosting-env-id: {{ .Values.hostingClusterId }}
  template:
    metadata:
      labels:
        app: planton-cloud-kube-agent
        company: {{ .Values.company }}
        hosting-env-id: {{ .Values.hostingClusterId }}
    spec:
      containers:
      - name: planton-cloud-kube-agent
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        env:
          - name: PLANTON_CLOUD_KUBE_AGENT_MACHINE_ACCOUNT_EMAIL
            value: {{ .Values.machineAccountEmail }}
          - name: PLANTON_CLOUD_KUBE_AGENT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: planton-cloud-machine-account
                key: client-secret
          - name: PLANTON_CLOUD_KUBE_AGENT_HOSTING_CLUSTER_ID
            value: {{ .Values.hostingClusterId }}
          - name: PLANTON_CLOUD_SERVICE_API_ENDPOINT
            value: {{ .Values.plantonCloudServiceApiEndpoint }}
          - name: OPEN_COST_API_ENDPOINT
            value: {{ .Values.openCostApiEndpoint }}
          - name: OPEN_COST_POLLING_INTERVAL_SECONDS
            value: {{ .Values.openCostPollingIntervalSeconds | quote }}
          - name: TOKEN_EXPIRATION_BUFFER_MINUTES
            value: {{ .Values.tokenExpirationBufferMinutes | quote }}
          - name: TOKEN_EXPIRATION_CHECK_INTERVAL_SECONDS
            value: {{ .Values.tokenExpirationCheckIntervalSeconds | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
