apiVersion: v1
kind: Secret
metadata:
  name: planton-cloud-machine-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: planton-cloud-kube-agent
    company: {{ .Values.company }}
    hosting-env-id: {{ .Values.hostingClusterId }}
type: Opaque
data:
  client-secret: {{ .Values.clientSecret | b64enc | quote }}
