{{ if .Values.createLetsEncryptDns01GcpDnsIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsEncryptDns01GcpDnsIssuerName }}
spec:
  acme:
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.gcpDnsProjectId }}
      - http01:
          ingress:
            class: istio
{{ end }}
