{{ if .Values.createLetsEncryptHttp01Issuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.createLetsEncryptHttp01Issuer }}
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production-http01
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        http01:
          ingress:
            class: istio
{{ end }}
